### ISSUE TITLE
프로젝트 개선 제안 드립니다!

### ISSUE THREAD

**Issue by minsoo-web** [WOK-AT/WOKAT_CLIENT#62]
안녕하세요,
우연히 깃허브의 추천 레포에 워캣이 뜨게 되어 레포 구경하다가 제안 드리고 싶은 사항들이 몇 가지 있어 이슈로 남겨봅니다!!

### 기능 명세

- .env 파일을 통해 API_URL을 숨깁니다.
- axios에 제네릭을 활용해서 typed 하게 서버 상태 관리를 적용합니다.

지금은 서버 API가 코드에 노출되어있습니다. 
하지만, public 레포인만큼 관리되어야 하는 정보라고 생각됩니다. 

또한, API에 요청을 보낼 때도 직접 요청 보내는 것이 아닌 nextjs의 redirect를 활용해서 우회하는 방법을 추천 드립니다.
지금은 네트워크 탭을 통해서 API 엔드 포인트를 확인할 수 있습니다...! 

<img width="509" alt="image" src="https://github.com/WOK-AT/WOKAT_CLIENT/assets/57122180/c11de70e-9725-4b22-8b04-492e2632efb9">

swagger 쓰실려나 하고 때려 맞춰봤습니다.
서버는 mongo 쓰시는 걸 아니까,,(백엔드도 public이여서 알게 되었습니다.) 하면서 다른 작업도 해볼 수 있었을 것 같아요! API URL 노출은 그만큼 위험합니다!

또한, axios에 제네릭을 활용하면 api 응답 결과를 typed 하게 받아볼 수 있다는 것 알고 계셨나요?!

Before

<img width="554" alt="image" src="https://github.com/WOK-AT/WOKAT_CLIENT/assets/57122180/7dd31422-4b89-4b84-8d4c-edefa6994fb8">

After

<img width="623" alt="image" src="https://github.com/WOK-AT/WOKAT_CLIENT/assets/57122180/c5c17e0f-4e93-441b-8835-c28aeea69657">

**Comment by leeseooo** [comment]
@minsoo-web 와앗 .. 꽤 크리티컬한 이슈를 놓치고 있었네요. 제네릭으로 response type을 추론시키는 부분도 새롭게 알게 되었어요 👍 말씀해 주신 사항들 반영해서 프로젝트 개선해볼게요 감사드립니다!

**Comment by f0rever0** [comment]
@minsoo-web  안녕하세요! 리뷰해주셔서 감사합니다! 말씀해주신 내용들 팀원들과 논의 후 반영해보겠습니다! ☺️
